name=str(input("Enter the name:"))
print("WELCOME TO CAREER PREDICTOR GAME")
print("---------------------------------------------------------------------------")
print("LEVEL--->1   (left brain vs right brain")
print("FIRST_ QUESTION :Draw a captial Q on you head and answer it ends(ANSWER:left or right")
FIRST_QUESTION=str(input("Enter right or left :"))
if FIRST_QUESTION=="r":
    print("------->right brain")
else:
    print("------->left brain")
print("SECOND_QUESTION :sit on a chair one leg above another (ANSWER:right or left")
SECOND_QUESTION=str(input("Enter right or left :"))
if SECOND_QUESTION=="r":
    print("------->right brain")
else:
    print("------->left brain")
print("THIRD_QUESTION :hand like chain thumb(ANSWER:right or left")
THIRD_QUESTION=str(input("Enter right or left :"))
if THIRD_QUESTION=="r":
    print("------->right brain")
else:
    print("------->left brain")
print("FOURTH_QUESTION : Which will you mostly listen lyrics or music")
FOURTH_QUESTION=str(input("Enter lyrics or music :"))
if FOURTH_QUESTION=="l":
    print("------->left brain")
else:
    print("------->right brain")
print("using right-R AND left-l")
print("make an answer for example :rrll")
print("if more than 3 combinations of r means ANSWER:rrrr")
print("if more than 3 combinations of l means ANSWER:llll")
print("if 2 equal number of rr and ll means    ANSWER:rrll")
result=str(input("Enter the result: example:rrll :"))
if result=="rrrr":
    print("------->Right Brain Person")
    print("You are a person with creative skill :)")
elif result=="llll":
    print("------->Left Brain Person")
    print("You are a person with practical skill :)")
elif result=="rrll":
    print("------->Both Right and Left Brain Person")
    print("You are a person with both creative and practical skill :)")
else:
    print("Invaild combination")
print("---------------------------------------------------------------------------")
print("LEVEL-->2    (LET FIND YOUR CHARACTER JOB")
print("first_QUESTION : YOU IS AN INTROVERT OR EXTROVERT")
first_QUESTION=str(input("Enter INTROVERT or EXTROVERT :"))
if first_QUESTION=="i":
    print("------->note the result 1: i")
else:
    print("------->note the result 1: e")
print("second_QUESTION : if you believe in fact enter(s) or if you believe in dreaming enter(n)")
second_QUESTION=str(input("Enter :fact or dreaming :"))
if second_QUESTION=="f":
    print("------->note the result2: s")
else:
    print("------->note the result2: n")
print("third_QUESTION : if you only work for you(mywork) or help in others work(otherwork)")
third_QUESTION=str(input("Enter :mywork or otherwork :"))
if third_QUESTION=="m":
    print("------->note your result3: t")
else:
    print("------->note your result3: f")
print("fourth_QUESTION :if you are planned person or spontanoeous person(onthattime)")
fourth_QUESTION=str(input("planned or spontanoeous :"))
if fourth_QUESTION=="p":
    print("------->note your result4: j")
else:
    print("------->note your result4: p")
print("make the combination of note result for example:estj")
result=str(input("enter the result :"))
if result=="estj":
    print("YOUR JOB LISTS (BLUE)")
    print("--------------------------------------------------------------------------- :)")
    print("1.Police")
    print("2.Miltary")
    print("3.Defence")
    print("4.Computer hardware engineer")
    print("5.Accountant")
    print("6.Manager")
    print("7.Sales Manager")
    print("8.Building Contractor")
elif result=="istj":
    print("YOUR JOB LISTS (BLUE)")
    print("--------------------------------------------------------------------------- :)")
    print("1.Police")
    print("2.Miltary")
    print("3.Defence")
    print("4.Computer hardware engineer")
    print("5.Accountant")
    print("6.Manager")
    print("7.Sales Manager")
    print("8.Building Contractor")
elif result=="estp":
    print("YOUR JOB LISTS (BLUE)")
    print("--------------------------------------------------------------------------- :)")
    print("1.Police")
    print("2.Miltary")
    print("3.Defence")
    print("4.Computer hardware engineer")
    print("5.Accountant")
    print("6.Manager")
    print("7.Sales Manager")
    print("8.Building Contractor")
elif result=="istp":
    print("YOUR JOB LISTS (BLUE)")
    print("--------------------------------------------------------------------------- :)")
    print("1.Police")
    print("2.Miltary")
    print("3.Defence")
    print("4.Computer hardware engineer")
    print("5.Accountant")
    print("6.Manager")
    print("7.Sales Manager")
    print("8.Building Contractor")
elif result=="esfj":
    print("YOUR JOB LIST (PINK)")
    print("--------------------------------------------------------------------------- :)")
    print("1.Caretaker")
    print("2.Teacher")
    print("3.Professor")
    print("4.social Worker")
    print("5.Airhoster")
    print("6.Customer Service")
    print("7.Equpiment repair")
    print("8.Receptionist")
elif result=="isfj":
    print("YOUR JOB LIST (PINK)")
    print("--------------------------------------------------------------------------- :)")
    print("1.Caretaker")
    print("2.Teacher")
    print("3.Professor")
    print("4.social Worker")
    print("5.Airhoster")
    print("6.Customer Service")
    print("7.Equpiment repair")
    print("8.Receptionist")
elif result=="esfp":
    print("YOUR JOB LIST (PINK)")
    print("--------------------------------------------------------------------------- :)")
    print("1.Caretaker")
    print("2.Teacher")
    print("3.Professor")
    print("4.social Worker")
    print("5.Airhoster")
    print("6.Customer Service")
    print("7.Equpiment repair")
    print("8.Receptionist")
elif result=="isfp":
    print("YOUR JOB LIST (PINK)")
    print("--------------------------------------------------------------------------- :)")
    print("1.Caretaker")
    print("2.Teacher")
    print("3.Professor")
    print("4.social Worker")
    print("5.Airhoster")
    print("6.Customer Service")
    print("7.Equpiment repair")
    print("8.Receptionist")
elif result=="entj":
    print("YOUR JOB LIST (RED)")
    print("--------------------------------------------------------------------------- :)")
    print("1.Engineer")
    print("2.Technical Content Writer")
    print("3.Software developer")
    print("4.Surgen(doctor)")
    print("5.Medical scientist")
    print("6.Producer")
    print("7.Real estate")
    print("8.Story writer")
elif result=="intj":
    print("YOUR JOB LIST (RED)")
    print("--------------------------------------------------------------------------- :)")
    print("1.Engineer")
    print("2.Technical Content Writer")
    print("3.Software developer")
    print("4.Surgen(doctor)")
    print("5.Medical scientist")
    print("6.Producer")
    print("7.Real estate")
    print("8.Story writer")
elif result=="entp":
    print("YOUR JOB LIST (RED)")
    print("--------------------------------------------------------------------------- :)")
    print("1.Engineer")
    print("2.Technical Content Writer")
    print("3.Software developer")
    print("4.Surgen(doctor)")
    print("5.Medical scientist")
    print("6.Producer")
    print("7.Real estate")
    print("8.Story writer")
elif result=="intp":
    print("YOUR JOB LIST (RED)")
    print("--------------------------------------------------------------------------- :)")
    print("1.Engineer")
    print("2.Technical Content Writer")
    print("3.Software developer")
    print("4.Surgen(doctor)")
    print("5.Medical scientist")
    print("6.Producer")
    print("7.Real estate")
    print("8.Story writer")
elif result=="enfj":
    print("YOUR JOB LIST (GREEN)")
    print("--------------------------------------------------------------------------- :)")
    print("1.Actor")
    print("2.Politician")
    print("3.Writer")
    print("4.Teacher")
    print("5.Tourist guide")
    print("6.Psycologist")
    print("7.Photograper")
    print("8.Fashion designer")
elif result=="infj":
    print("YOUR JOB LIST (GREEN)")
    print("--------------------------------------------------------------------------- :)")
    print("1.Actor")
    print("2.Politician")
    print("3.Writer")
    print("4.Teacher")
    print("5.Tourist guide")
    print("6.Psycologist")
    print("7.Photograper")
    print("8.Fashion designer")
elif result=="enfp":
    print("YOUR JOB LIST (GREEN)")
    print("--------------------------------------------------------------------------- :)")
    print("1.Actor")
    print("2.Politician")
    print("3.Writer")
    print("4.Teacher")
    print("5.Tourist guide")
    print("6.Psycologist")
    print("7.Photograper")
    print("8.Fashion designer")
elif result=="infp":
    print("YOUR JOB LIST (GREEN)")
    print("--------------------------------------------------------------------------- :)")
    print("1.Actor")
    print("2.Politician")
    print("3.Writer")
    print("4.Teacher")
    print("5.Tourist guide")
    print("6.Psycologist")
    print("7.Photograper")
    print("8.Fashion designer")
else:
    print("Invalid combination")


